name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main  # Ana dalı (main branch) izler. Başka bir dal kullanıyorsanız, orayı da ekleyebilirsiniz.

jobs:
  build:
    runs-on: windows-latest  # Windows ortamında çalıştırılacak

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Repo'yu çek

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Python sürümünü belirle

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas  # PyInstaller ve pandas yükleniyor

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed operatör_uygulaması.py  # Burada dosyanızın ismini yazın

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v2  # `v2` sürümünü kullanıyoruz
      with:
        name: built-exe
        path: ./dist/*.exe  # EXE dosyasını yükler
